name: Captura
description: Capture Screen, Audio, Cursor, Mouse Clicks and Keystrokes
author: Mathew Sachin

exclude: ["Gemfile", "Gemfile.lock", "README.md"]

accounts:
  gitter: "MathewSachin/Screna"
  github: "MathewSachin/Captura"
  google-analytics: "UA-70778035-3"

links:
  gitter: https://gitter.im/MathewSachin/Screna
  appveyor: https://ci.appveyor.com/project/MathewSachin/Captura
  github: https://github.com/MathewSachin/Captura
  gratipay: https://gratipay.com/Screna
  patreon: https://www.patreon.com/MathewSachin
  paypal: https://www.paypal.com/MathewSachin